### PR TITLE
RHODS Users Section

### PR DESCRIPTION
**Pull request by strangiato**

### CODE REVIEW

**Review by rsriniva — CHANGES_REQUESTED** [review]
Great start! Please address my comments:

- As per comments in previous sections PR, please split into initial 2 or 3 paras of theory narrative ad then add an exercise sub-section, followed by a References at the bottom
- Numbered steps for exercise.
- Any oc CLI tips? for troubleshooting, checking, validating etc etc
- Explain more clearly the relationship between OCP parts of users and roles and RHODS users and groups

**Comment by strangiato** [comment]
> * As per comments in previous sections PR, 

I'm unsure what this is referring to.

> please split into initial 2 or 3 paras of theory narrative 

Updated, let me know if this is what you were looking for

> add an exercise sub-section, 

I added a small exercise at the end.  I'm not sure that this section lends itself very well to exercises.  Let me know if you have a suggestion for an additional exercise.  

Also, I'm not exactly sure how to approach setting up the exercises without any context for what the exercise environment will be or what will be setup for users out of the box.

> followed by a References at the bottom

Not sure what you mean by this.  Are you looking for a list of additional references for links to other things talking about this?  I provided a few relevant links to some docs that covered topics I felt fell outside of the scope of this course throughout the page so I'm not sure if you are looking to just repeat those links at the bottom.

> * Any oc CLI tips? for troubleshooting, checking, validating etc etc

I'm not sure what all would be relevant here.  If you have any specific items that you see that could use some additional info for these let me know.

> * Explain more clearly the relationship between OCP parts of users and roles and RHODS users and groups

I tried to clear up a bit.  Let me know if that helps.

**Comment by strangiato** [comment]
@rsriniva Please take a look at my comments above.

**Comment by jhurlocker** [comment]
- [https://redhatquickcourses.github.io/rhods-admin/pr-preview/pr-4/rhods-admin/1.33/chapter2/users.html#_admin_access](https://redhatquickcourses.github.io/rhods-admin/pr-preview/pr-4/rhods-admin/1.33/chapter2/users.html#_admin_access) 
Change **Additional** to **Additionally**
_**Additional**, a group called rhods-admins is automatically created, and any user added to that group will be granted admin permissions._

- Is it **OpenShift AI** or **Openshift.AI**? If it's OpenShift AI update throughout the page.

- Is there already a section that describes how to login to OpenShift using the CLI tool? If not, we might want to create it in another section.
_To add users to the rhods-admins group, run the following command:
oc adm groups add-users rhods-admins my-user1 my-user2_

- [https://redhatquickcourses.github.io/rhods-admin/pr-preview/pr-4/rhods-admin/1.33/chapter2/users.html#_managing_dashboard_permissions_with_gitops](https://redhatquickcourses.github.io/rhods-admin/pr-preview/pr-4/rhods-admin/1.33/chapter2/users.html#_managing_dashboard_permissions_with_gitops)
Should **objected** be changed to **object**?
_The User and group settings in the Openshift.AI Dashboard can also be managed using the OdhDashboardConfigs **objected**_

- [https://redhatquickcourses.github.io/rhods-admin/pr-preview/pr-4/rhods-admin/1.33/chapter2/users.html#_exercise](https://redhatquickcourses.github.io/rhods-admin/pr-preview/pr-4/rhods-admin/1.33/chapter2/users.html#_exercise)
Do you think screenshots would help in the exercise?

**Review by jramcast — APPROVED** [review]
This section is very well written and with lots of details. Good job @strangiato! I have just added a couple of minor comments for you to consider, but no need for rereview. You can go ahead and merge.

**Review by rsriniva — APPROVED** [review]
LGTM for now. Let's merge this after resolving the merge conflicts

**Pull request merged**
